### ISSUE TITLE
Add speciesProfile information

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-macroinvertebrates#40]
Following terms could be populated based on habitat:

habitat | isMarine | isFreshwater | isTerrestrial
--- | --- | --- | ---
F | false | true | false
M | true | false | false
M/B | true | false | false
F/B | false | true | false
B | true?? | true?? | false

For definitions, see http://rs.gbif.org/extension/gbif/1.0/speciesprofile.xml

@timadriaens can you confirm?

**Comment by peterdesmet** [comment]
Or... should we only add this information to the unified checklist?

**Comment by peterdesmet** [comment]
Decided to map this habitat information to speciesProfile and no longer publish in the description extension. Ask Pieter what to do with brackish.

**Comment by LienReyserhove** [comment]
Pieter agrees with the suggestions listed above, so we have a green light here.
I will make a new PR.

**Comment by peterdesmet** [comment]
So B = freshwater AND marine, while M/B and F/B only match with one?

**Comment by timadriaens** [comment]
well, yes, in a way that's correct. Brackish is in between marine and fresh water, depending on salinity. So I guess M/B are primarily marine species that also occur in more brackish conditions of the estuary or are dependent of it at some lifestage for their development. Of course, difficult to put species in one box sometimes. For example, chinese mitten crabs are exclusively marine as juveniles, but then grow up in the estuary in brackish conditions and migrate upstream to freshwater habitats.

In fact it's mixing up terms. In the indicators, we use "estuarine" as an environment for brackish conditions and we lump marine/estuarine because a lot of marine species (mostly crustaceans) disperse to the estuary also and because we have lots of data on aliens from the Scheldt estuary.

So lumping F/B, M/B and B in "estuarine" might be an option (but this can be done in the unified checklist).

**Comment by peterdesmet** [comment]
The thing is: we don’t have an estuarine option, so we have to lump them here. So, how would you?

**Comment by timadriaens** [comment]
Estuaries is 9.10 in the IUCN Habitat Vocabulary... but is not in the species profile (which contains a strange mixture of things actually). One to note down when opportunity arises to update "species profile" with a category "estuarine"...

**Comment by timadriaens** [comment]
so F/B, M/B are ok in the table to lump in freshwater and marine respectively; but brackish is neither so leave blank

**Comment by peterdesmet** [comment]
Ok, but those species will then be absent from that indicator chart.

**Comment by LienReyserhove** [comment]
Pieter Boets agreed with our approach to use both ´isFreshwater´ and ´isMarine´ for species in brackish habitat. However, I understand why you would leave information for brackish species blank. 
I do think it's a petty to loose this information...

**Comment by peterdesmet** [comment]
Well, if Pieter agrees, I think we can leave it at that. Closing issue.
